### ISSUE TITLE
Question - Interested in contributing

### ISSUE THREAD

**Issue by MZwillus** [JvilleyWordpressTheme/Jvilley-wp-magazine-theme#1]
Hey there,

I am a Theme Reviewer at the WordPress Theme repositories and I'm wondering if you are planning to upload it there as well?

I'm very interested in contributing, although it would be the first theme I'm writing myself.
I only did customizations in the past.

Let me know if you are interested anyways.

Regards
Malte

BTW:
Saw your message in the Slack Channel.

**Comment by jishnurajm** [comment]
Hi, glad to know that you are willing to help us. Of course, we are planning to upload the theme on WordPress as well. We hope you have read our mission and vision. We are not planning to do a commercial template. It is free, and it is always will be.

**Comment by MZwillus** [comment]
I did, I was asking because themes in the repository have certain requirements and are limited in some way.

**Comment by MZwillus** [comment]
I did some work but I'm unable to push my branch.

**Comment by jishnurajm** [comment]
sorry for the interruptions. you can now able to push and other edits

**Comment by MZwillus** [comment]
It's fine. I'm just not sure how much I'm gonna be able to do, but I'll do my best :-)

**Comment by jishnurajm** [comment]
jishnurajm@gmail.com this is my email id. you can contact me at any time through Hangout or through gmail

**Comment by MZwillus** [comment]
Alright, saved it. You can delete it from this issue if you want.
