### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by terrence-gonsalves** [JvilleyWordpressTheme/Jvilley-wp-magazine-theme#3]
Hi there, I am interesting contributing if that's ok. I was wondering if you had a project plan? What would the workflow look like? Would we just fork the repository and submit pull requests? Would you rather add as contributors?

Looking forward to you response.

**Comment by jishnurajm** [comment]
Hi mate
It's glad to know that you are interested to our project
As your wish. Let me know which method suits for you."

**Comment by jishnurajm** [comment]
I added you as an contributor
